//
//  CGFloat+.swift
//  Routee-iOS
//
//  Generated by DesignTokens/scripts/build-ios-colors.mjs.
//

import CoreGraphics

// swiftlint:disable identifier_name
extension CGFloat {
    static let s2: CGFloat = 2
    static let s4: CGFloat = 4
    static let s6: CGFloat = 6
    static let s8: CGFloat = 8
    static let s10: CGFloat = 10
    static let s12: CGFloat = 12
    static let s14: CGFloat = 14
    static let s16: CGFloat = 16
    static let s18: CGFloat = 18
    static let s20: CGFloat = 20
    static let s24: CGFloat = 24
    static let s32: CGFloat = 32
    static let s80: CGFloat = 80

    static let r8: CGFloat = 8
    static let r12: CGFloat = 12
    static let r16: CGFloat = 16
    static let r20: CGFloat = 20
    static let r22: CGFloat = 22
    static let r24: CGFloat = 24
    static let r32: CGFloat = 32
}
// swiftlint:enable identifier_name
