//
//  UIColor+.swift
//  Routee-iOS
//
//  Generated by DesignTokens/scripts/build-ios-colors.mjs.
//

import UIKit

// swiftlint:disable file_length identifier_name
extension UIColor {
    static var bg_cta_primary: UIColor {
        routeeColor(
            name: "bg_cta_primary",
            red: 0.388235,
            green: 0.964706,
            blue: 0.992157,
            alpha: 1.000000
        )
    }

    static var bg_cta_secondary: UIColor {
        routeeColor(
            name: "bg_cta_secondary",
            red: 0.203922,
            green: 0.898039,
            blue: 0.949020,
            alpha: 0.100000
        )
    }

    static var bg_primary: UIColor {
        routeeColor(
            name: "bg_primary",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 1.000000
        )
    }

    static var black_30: UIColor {
        routeeColor(
            name: "black_30",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.300000
        )
    }

    static var black_40: UIColor {
        routeeColor(
            name: "black_40",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.400000
        )
    }

    static var black_50: UIColor {
        routeeColor(
            name: "black_50",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.500000
        )
    }

    static var black_60: UIColor {
        routeeColor(
            name: "black_60",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.600000
        )
    }

    static var black_80: UIColor {
        routeeColor(
            name: "black_80",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.800000
        )
    }

    static var brand_primary: UIColor {
        routeeColor(
            name: "brand_primary",
            red: 0.003922,
            green: 0.870588,
            blue: 0.937255,
            alpha: 1.000000
        )
    }

    static var brand_secondary: UIColor {
        routeeColor(
            name: "brand_secondary",
            red: 0.898039,
            green: 1.000000,
            blue: 0.309804,
            alpha: 1.000000
        )
    }

    static var dim_primary: UIColor {
        routeeColor(
            name: "dim_primary",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.600000
        )
    }

    static var dim_secondary: UIColor {
        routeeColor(
            name: "dim_secondary",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 0.800000
        )
    }

    static var grey_200: UIColor {
        routeeColor(
            name: "grey_200",
            red: 0.666667,
            green: 0.674510,
            blue: 0.694118,
            alpha: 1.000000
        )
    }

    static var grey_300: UIColor {
        routeeColor(
            name: "grey_300",
            red: 0.513726,
            green: 0.525490,
            blue: 0.556863,
            alpha: 1.000000
        )
    }

    static var grey_400: UIColor {
        routeeColor(
            name: "grey_400",
            red: 0.419608,
            green: 0.431373,
            blue: 0.470588,
            alpha: 1.000000
        )
    }

    static var grey_50: UIColor {
        routeeColor(
            name: "grey_50",
            red: 0.929412,
            green: 0.929412,
            blue: 0.933333,
            alpha: 1.000000
        )
    }

    static var grey_500: UIColor {
        routeeColor(
            name: "grey_500",
            red: 0.274510,
            green: 0.290196,
            blue: 0.337255,
            alpha: 1.000000
        )
    }

    static var grey_600: UIColor {
        routeeColor(
            name: "grey_600",
            red: 0.250980,
            green: 0.262745,
            blue: 0.305882,
            alpha: 1.000000
        )
    }

    static var grey_800: UIColor {
        routeeColor(
            name: "grey_800",
            red: 0.152941,
            green: 0.160784,
            blue: 0.184314,
            alpha: 1.000000
        )
    }

    static var grey_900: UIColor {
        routeeColor(
            name: "grey_900",
            red: 0.113725,
            green: 0.121569,
            blue: 0.141176,
            alpha: 1.000000
        )
    }

    static var lime_100: UIColor {
        routeeColor(
            name: "lime_100",
            red: 0.956863,
            green: 1.000000,
            blue: 0.768627,
            alpha: 1.000000
        )
    }

    static var lime_200: UIColor {
        routeeColor(
            name: "lime_200",
            red: 0.933333,
            green: 1.000000,
            blue: 0.560784,
            alpha: 1.000000
        )
    }

    static var lime_300: UIColor {
        routeeColor(
            name: "lime_300",
            red: 0.898039,
            green: 1.000000,
            blue: 0.309804,
            alpha: 1.000000
        )
    }

    static var lime_400: UIColor {
        routeeColor(
            name: "lime_400",
            red: 0.858824,
            green: 0.980392,
            blue: 0.105882,
            alpha: 1.000000
        )
    }

    static var mint_100: UIColor {
        routeeColor(
            name: "mint_100",
            red: 0.807843,
            green: 0.996078,
            blue: 1.000000,
            alpha: 1.000000
        )
    }

    static var mint_200: UIColor {
        routeeColor(
            name: "mint_200",
            red: 0.639216,
            green: 0.984314,
            blue: 0.996078,
            alpha: 1.000000
        )
    }

    static var mint_300: UIColor {
        routeeColor(
            name: "mint_300",
            red: 0.388235,
            green: 0.964706,
            blue: 0.992157,
            alpha: 1.000000
        )
    }

    static var mint_400: UIColor {
        routeeColor(
            name: "mint_400",
            red: 0.113725,
            green: 0.905882,
            blue: 0.952941,
            alpha: 1.000000
        )
    }

    static var mint_500: UIColor {
        routeeColor(
            name: "mint_500",
            red: 0.003922,
            green: 0.870588,
            blue: 0.937255,
            alpha: 1.000000
        )
    }

    static var mint_600: UIColor {
        routeeColor(
            name: "mint_600",
            red: 0.015686,
            green: 0.631373,
            blue: 0.713726,
            alpha: 1.000000
        )
    }

    static var mint_700: UIColor {
        routeeColor(
            name: "mint_700",
            red: 0.043137,
            green: 0.501961,
            blue: 0.576471,
            alpha: 1.000000
        )
    }

    static var mint_800: UIColor {
        routeeColor(
            name: "mint_800",
            red: 0.074510,
            green: 0.400000,
            blue: 0.466667,
            alpha: 1.000000
        )
    }

    static var mint_900: UIColor {
        routeeColor(
            name: "mint_900",
            red: 0.078431,
            green: 0.333333,
            blue: 0.396078,
            alpha: 1.000000
        )
    }

    static var recap_green: UIColor {
        routeeColor(
            name: "recap_green",
            red: 0.450980,
            green: 0.937255,
            blue: 0.686013,
            alpha: 1.000000
        )
    }

    static var recap_lime: UIColor {
        routeeColor(
            name: "recap_lime",
            red: 0.898039,
            green: 1.000000,
            blue: 0.309804,
            alpha: 1.000000
        )
    }

    static var recap_mint: UIColor {
        routeeColor(
            name: "recap_mint",
            red: 0.388235,
            green: 0.964706,
            blue: 0.992157,
            alpha: 1.000000
        )
    }

    static var recap_navy: UIColor {
        routeeColor(
            name: "recap_navy",
            red: 0.098039,
            green: 0.125490,
            blue: 0.192157,
            alpha: 1.000000
        )
    }

    static var recap_orange: UIColor {
        routeeColor(
            name: "recap_orange",
            red: 0.974495,
            green: 0.347637,
            blue: 0.119689,
            alpha: 1.000000
        )
    }

    static var recap_pink: UIColor {
        routeeColor(
            name: "recap_pink",
            red: 1.000000,
            green: 0.639243,
            blue: 0.735445,
            alpha: 1.000000
        )
    }

    static var recap_purple: UIColor {
        routeeColor(
            name: "recap_purple",
            red: 0.671604,
            green: 0.621081,
            blue: 1.000000,
            alpha: 1.000000
        )
    }

    static var recap_white: UIColor {
        routeeColor(
            name: "recap_white",
            red: 1.000000,
            green: 1.000000,
            blue: 1.000000,
            alpha: 1.000000
        )
    }

    static var static_black: UIColor {
        routeeColor(
            name: "static_black",
            red: 0.062745,
            green: 0.066667,
            blue: 0.074510,
            alpha: 1.000000
        )
    }

    static var static_white: UIColor {
        routeeColor(
            name: "static_white",
            red: 1.000000,
            green: 1.000000,
            blue: 1.000000,
            alpha: 1.000000
        )
    }

    static var status_error: UIColor {
        routeeColor(
            name: "status_error",
            red: 0.862745,
            green: 0.286275,
            blue: 0.286275,
            alpha: 1.000000
        )
    }

    static var status_info: UIColor {
        routeeColor(
            name: "status_info",
            red: 0.039216,
            green: 0.525490,
            blue: 0.874510,
            alpha: 1.000000
        )
    }

    static var status_success: UIColor {
        routeeColor(
            name: "status_success",
            red: 0.133333,
            green: 0.772549,
            blue: 0.368627,
            alpha: 1.000000
        )
    }

    static var status_warning: UIColor {
        routeeColor(
            name: "status_warning",
            red: 0.960784,
            green: 0.619608,
            blue: 0.043137,
            alpha: 1.000000
        )
    }

    static var surface_tinted: UIColor {
        routeeColor(
            name: "surface_tinted",
            red: 0.203922,
            green: 0.898039,
            blue: 0.949020,
            alpha: 0.100000
        )
    }

    static var white_10: UIColor {
        routeeColor(
            name: "white_10",
            red: 1.000000,
            green: 1.000000,
            blue: 1.000000,
            alpha: 0.100000
        )
    }

    static var white_30: UIColor {
        routeeColor(
            name: "white_30",
            red: 1.000000,
            green: 1.000000,
            blue: 1.000000,
            alpha: 0.300000
        )
    }

    static var white_60: UIColor {
        routeeColor(
            name: "white_60",
            red: 1.000000,
            green: 1.000000,
            blue: 1.000000,
            alpha: 0.600000
        )
    }

    private static func routeeColor(
        name: String,
        red: CGFloat,
        green: CGFloat,
        blue: CGFloat,
        alpha: CGFloat
    ) -> UIColor {
        UIColor(named: name) ?? UIColor(
            red: red,
            green: green,
            blue: blue,
            alpha: alpha
        )
    }
}
// swiftlint:enable file_length identifier_name
